/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package employee.management.system.app;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
